name: generator-generic-ossf-slsa3-publish

on:
  workflow_dispatch:
  release:
    types:
      - published
  push:
    tags:
      - 'v*'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create source archive
        shell: bash
        run: |
          set -euo pipefail
          git archive --format=tar.gz --output hitechcloud_domains.tar.gz HEAD

      - name: Generate subject hashes
        id: hash
        shell: bash
        run: |
          set -euo pipefail
          echo "hashes=$(sha256sum hitechcloud_domains.tar.gz | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: hitechcloud_domains.tar.gz
          if-no-files-found: error

  provenance:
    needs:
      - build
    permissions:
      actions: read
      contents: write
      id-token: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: ${{ needs.build.outputs.hashes }}
      upload-assets: true
